name: flutter_android_volume_keydown
description: A simple plugin for listening to the Android volume keydown event
version: 1.0.0
homepage: https://github.com/dart-tools/flutter_android_volume_keydown

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.darttools.flutter_android_volume_keydown
        pluginClass: FlutterAndroidVolumeKeydownPlugin
